### ISSUE TITLE
在typora中为何不能显示为相应格式？

### ISSUE THREAD

**Issue by A-Pai** [Anesck/M-D-R_learning_notes#1]
![QQ截图20210518205917](https://user-images.githubusercontent.com/5112397/118655367-0fe20d80-b81c-11eb-8844-42f25ac36c14.jpg)

**Comment by Anesck** [comment]
菜单栏 -&gt; 文件 -&gt; 偏好设置 -&gt; Markdown -&gt; 在 ‘Markdown 扩展语法’ 中勾选内联公式。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月18日(星期二) 晚上9:00
收件人: "Anesck/M-D-R_learning_notes";
抄送: "Subscribed";
主题: [Anesck/M-D-R_learning_notes] 在typora中为何不能显示为相应格式？ (#1)





 

 
&mdash;

**Comment by A-Pai** [comment]
感谢指点，文档做的很漂亮，非常感谢您的辛勤工作
刚才这样设置后，又发现新问题：
![image](https://user-images.githubusercontent.com/5112397/118670996-aec13680-b829-11eb-9925-c74a6c7eda84.png)

**Comment by Anesck** [comment]
菜单栏 -&gt; 文件 -&gt; 偏好设置 -&gt; Markdown -&gt; 在 ‘公式’ 中勾选自动添加序号，关于格式相关问题，您可以先了解下偏好设置中的各选项，会有算帮助的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anesck/M-D-R_learning_notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 晚上10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Anesck/M-D-R_learning_notes] 在typora中为何不能显示为相应格式？ (#1)





 
感谢指点，文档做的很漂亮，非常感谢您的辛勤工作
 刚才这样设置后，又发现新问题：

**Comment by A-Pai** [comment]
问题解决了，谢谢您的建议，我会仔细学的
